version: '3.8'
services:

  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile-account
    container_name: account-service
    ports:
      - "8082:8082"
    depends_on:
      - customer-service
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  customer-service:
    build:
      context: ./customer-service
      dockerfile: Dockerfile-customer
    container_name: customer-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  event-service:
    build:
      context: ./event-service
      dockerfile: Dockerfile-event
    container_name: event-service
    ports:
      - "8083:8083"
    depends_on:
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper